- name: Email server setup
  hosts: email
  remote_user: root
  tasks:
    - name: Install postfix
      ansible.builtin.package:
        name: postfix
        state: present
    - name: Copy config file
      register: config_file
      ansible.builtin.copy:
        src: ../config/postfix/main.cf
        dest: /etc/postfix/main.cf
    - name: Copy master file
      register: master_file
      ansible.builtin.copy:
        src: ../config/postfix/master.cf
        dest: /etc/postfix/master.cf

    # filter stuff
    - name: Install ruby
      ansible.builtin.package:
        name: ruby-full
        state: present
    - name: Create filter user
      ansible.builtin.user:
        name: filter
    - name: Create filter directory
      ansible.builtin.file:
        path: /var/spool/filter
        state: directory
        owner: filter
        mode: "0700"
    - name: Copy filter script
      ansible.builtin.copy:
        src: ../scripts/filter_script
        dest: /opt/filter_script
    - name: Create ruby processing script directory
      ansible.builtin.file:
        path: /opt/git
        state: directory
    - name: Install git
      ansible.builtin.package:
        name: git
        state: present
    - name: Clone ruby processing script
      register: ruby_processing_script
      ansible.builtin.git:
        repo: git@github.com:jackloughran/kindlize-email.git
        dest: /opt/git/kindlize-email
    - name: Install bundler
      ansible.builtin.shell:
        cmd: gem install bundler && touch /opt/bundler_installed.txt
        creates: /opt/bundler_installed.txt
    - name: Install gcc for nokogiri
      ansible.builtin.package:
        name: build-essential
        state: present
    - name: Install zlib for nokogiri
      ansible.builtin.package:
        name: zlib1g-dev
        state: present
    - name: Run ruby processing script setup
      # when: ruby_processing_script.changed
      ansible.builtin.shell:
        chdir: /opt/git/kindlize-email
        cmd: ./bin/setup
    - name: Create calibre directory
      ansible.builtin.file:
        path: /opt/calibre
        state: directory
    - name: Install libgl1 for calibre
      ansible.builtin.package:
        name: libgl1-mesa-glx
        state: present
    - name: Install qt for calibre
      ansible.builtin.package:
        name: qt5-default
        state: present
    - name: Install calibre
      ansible.builtin.shell:
        chdir: /opt/calibre
        cmd: wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sh /dev/stdin
        creates: /opt/calibre/ebook-convert

    - name: Restart postfix
      when: config_file.changed or master_file.changed
      ansible.builtin.systemd:
        name: postfix
        state: restarted
